'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Bookmark, Check, Clock3, Flame, Plus, Star } from 'lucide-react';
import { useFitLog } from '@/context/FitLogContext';

export default function DetailClient({ id }) {
  const [workout, setWorkout] = useState(null); const [loading, setLoading] = useState(true);
  const { plan, saved, addToPlan, toggleSaved } = useFitLog();
  useEffect(()=>{ fetch(`/api/workouts/${id}`).then(r=>{if(!r.ok) throw new Error(); return r.json()}).then(setWorkout).catch(()=>setWorkout(null)).finally(()=>setLoading(false)); },[id]);
  if (loading) return <div className="container-fit py-20"><div className="spinner mx-auto"/></div>;
  if (!workout) return <div className="container-fit py-24 text-center"><h1 className="display text-5xl">WORKOUT NOT FOUND</h1><Link className="lime-btn mt-6 inline-flex rounded-md px-5 py-3 text-xs" href="/">Back to workouts</Link></div>;
  const inPlan = plan.some(x=>x.id===workout.id), isSaved=saved.some(x=>x.id===workout.id);
  const specs=[['EQUIPMENT',workout.equipment],['DIFFICULTY',workout.difficulty],['SETS',workout.sets],['REPS',workout.reps],['DURATION',`${workout.duration} min`],['CALORIES',`${workout.caloriesBurned} kcal`],['RATING',workout.rating]];
  return <div className="container-fit py-8 sm:py-10"><Link href="/" className="mb-7 inline-flex items-center gap-2 text-xs text-[#888c96] hover:text-white"><ArrowLeft size={14}/> Back to library</Link><div className="grid gap-8 lg:grid-cols-[1fr_1fr] lg:items-start"><div className="overflow-hidden rounded-xl border border-[#272a33] bg-[#121419]"><img src={workout.image} alt={workout.name} className="aspect-square h-auto w-full object-cover"/></div><div><p className="mb-3 text-[10px] font-bold tracking-[.15em] text-lime">WORKOUT DETAILS</p><h1 className="display text-5xl uppercase leading-[.9] sm:text-6xl">{workout.name}</h1><p className="mt-4 text-sm leading-6 text-[#91959f]">{workout.description}</p><div className="mt-4 flex flex-wrap gap-2">{workout.muscleGroups.map(t=><span key={t} className="rounded-full bg-lime px-3 py-1 text-[10px] font-extrabold text-black">{t}</span>)}</div><div className="mt-7 overflow-hidden rounded-xl border border-[#292c35] bg-[#12151a]">{specs.map(([k,v])=><div key={k} className="flex items-center justify-between border-b border-[#252832] px-4 py-3 last:border-b-0"><span className="text-[10px] font-bold tracking-[.08em] text-[#727680]">{k}</span><span className="text-xs font-semibold text-[#e2e4e8]">{v}</span></div>)}</div><div className="mt-8"><h2 className="display text-2xl uppercase">Instructions</h2><ol className="mt-4 space-y-3">{workout.instructions.map((s,i)=><li key={s} className="flex gap-3 text-sm leading-5 text-[#a3a6ae]"><span className="flex h-6 w-6 shrink-0 items-center justify-center rounded-full border border-[#3a3e48] text-[10px] font-bold text-lime">{i+1}</span><span>{s}</span></li>)}</ol></div><div className="mt-8 flex flex-col gap-3 sm:flex-row"><button disabled={inPlan || plan.length>=5} onClick={()=>addToPlan(workout)} className={`lime-btn inline-flex items-center justify-center gap-2 rounded-md px-5 py-3 text-xs ${inPlan||plan.length>=5?'cursor-not-allowed opacity-50':''}`}>{inPlan?<Check size={15}/>:<Plus size={15}/>} {inPlan?'Already in today\'s plan':'Add to today\'s plan'}</button><button onClick={()=>toggleSaved(workout)} className="dark-btn inline-flex items-center justify-center gap-2 rounded-md px-5 py-3 text-xs">{isSaved?<Check size={15}/>:<Bookmark size={15}/>} {isSaved?'Saved':'Save for later'}</button></div></div></div></div>;
}
