'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { ArrowDownUp, Dumbbell, Flame, Search } from 'lucide-react';
import PlanCard from '@/components/PlanCard';
import { useFitLog } from '@/context/FitLogContext';

export default function MyPlanPage() {
  const { plan, saved } = useFitLog();
  const [tab,setTab]=useState('plan'); const [sort,setSort]=useState('duration'); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true);
  useEffect(()=>{ const t=setTimeout(()=>setLoading(false),450); return ()=>clearTimeout(t); },[]);
  useEffect(()=>{ const params=new URLSearchParams(window.location.search); if(params.get('tab')==='saved') setTab('saved'); },[]);
  const current=tab==='plan'?plan:saved;
  const items=useMemo(()=>[...current].filter(w=>`${w.name} ${w.muscleGroups?.join(' ')}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='calories'?b.caloriesBurned-a.caloriesBurned:sort==='rating'?b.rating-a.rating:a.duration-b.duration),[current,search,sort]);
  const minutes=plan.reduce((s,w)=>s+w.duration,0), calories=plan.reduce((s,w)=>s+w.caloriesBurned,0);
  return <div className="container-fit py-10"><div><h1 className="display text-5xl uppercase sm:text-6xl">My Plan</h1><p className="mt-1 text-sm text-[#858994]">Cap of five lifts for today. Finish them, then load more.</p></div><div className="mt-7 grid grid-cols-3 overflow-hidden rounded-xl border border-[#252832] bg-[#111318]"><Metric label="Exercises" value={plan.length}/><Metric label="Minutes" value={minutes}/><Metric label="Calories" value={calories}/></div><div className="mt-7 flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex w-fit rounded-md border border-[#292c35] bg-[#111318] p-1"><button onClick={()=>setTab('plan')} className={`rounded px-4 py-2 text-xs ${tab==='plan'?'bg-[#252a34] text-white':'text-[#7e828c]'}`}>Today&apos;s Plan</button><button onClick={()=>setTab('saved')} className={`rounded px-4 py-2 text-xs ${tab==='saved'?'bg-[#252a34] text-white':'text-[#7e828c]'}`}>Saved</button></div><div className="flex flex-col gap-2 sm:flex-row"><label className="flex h-10 items-center gap-2 rounded-md border border-[#2a2d35] bg-[#101217] px-3 text-xs text-[#777b85]"><Search size={14}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search" className="w-36 bg-transparent outline-none"/></label><label className="flex h-10 items-center gap-2 rounded-md border border-[#2a2d35] bg-[#101217] px-3 text-xs text-[#a2a5ad]"><ArrowDownUp size={14}/><span>Sort By</span><select value={sort} onChange={e=>setSort(e.target.value)} className="bg-transparent outline-none"><option value="duration">Duration</option><option value="calories">Calories</option><option value="rating">Rating</option></select></label></div></div><div className="mt-4 min-h-[300px] border border-[#252832] bg-[#0e1014] p-4 sm:p-5">{loading?<div className="flex min-h-[260px] items-center justify-center"><div className="flex items-center gap-3 text-sm text-[#7e828c]"><span className="spinner"/> Loading workouts…</div></div>:items.length?<div className="space-y-3">{items.map(w=><PlanCard key={w.id} workout={w} savedTab={tab==='saved'}/>)}</div>:<div className="flex min-h-[260px] flex-col items-center justify-center text-center"><Dumbbell className="mb-4 text-[#3e424b]" size={34}/><h2 className="display text-3xl">Nothing Here Yet</h2><p className="mt-2 text-xs text-[#777b85]">Browse the library and add a lift to get today moving.</p><Link href="/" className="lime-btn mt-5 rounded-md px-5 py-3 text-[10px] uppercase">Go to workouts</Link></div>}</div></div>;
}
function Metric({label,value}){return <div className="border-r border-[#252832] px-4 py-5 last:border-r-0 sm:px-7"><p className="text-[10px] font-semibold text-[#747883]">{label}</p><p className="display mt-1 text-3xl sm:text-4xl">{value}</p></div>}
